name: microbiome
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.3
  - bioconductor-phyloseq
  - bioconductor-biostrings
  - r-igraph
  - r-vegan
  - r-ggplot2
  - r-dplyr
  - r-remotes
